# Generated by Django 5.2.2 on 2025-06-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
